<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class DestinationSeeder extends Seeder
{
    public function run(): void
    {
        DB::statement('DELETE FROM destinations');
        // Note: No AUTO_INCREMENT reset needed — SQLite handles IDs automatically

        $now   = Carbon::now()->toDateTimeString();
        $batch = [];
        $i     = 1;
        $total = 0;

        foreach ($this->destinations() as $d) {
            $batch[] = [
                'name'          => $d[0],
                'country'       => $d[1],
                'region'        => $d[2] ?? $this->determineRegion($d[1]),
                'category'      => $d[3] ?? 'general',
                'mood'          => $d[4] ?? 'cultural',
                'price_from'    => $d[5] ?? rand(500, 3000),
                'description'   => $d[6] ?? $this->generateDescription($d[0], $d[1]),
                'image_url'     => $d[7] ?? $this->getPlaceholderImage($d[0]),
                'badge'         => $d[8] ?? null,
                'is_hidden_gem' => $d[9] ?? 0,
                'match_score'   => $d[10] ?? null,
                'is_active'     => 1,
                'sort_order'    => $i++,
                'created_at'    => $now,
                'updated_at'    => $now,
            ];
            $total++;

            if (count($batch) >= 100) {
                DB::table('destinations')->insert($batch);
                $batch = [];
                $this->command->info("  ✓ Inserted {$total} destinations...");
            }
        }

        if (!empty($batch)) {
            DB::table('destinations')->insert($batch);
        }

        $count      = DB::table('destinations')->count();
        $hiddenGems = DB::table('destinations')->where('is_hidden_gem', 1)->count();

        $this->command->info('');
        $this->command->info('✓========================================✓');
        $this->command->info('  SEEDING COMPLETE');
        $this->command->info('✓========================================✓');
        $this->command->info("  Total destinations : {$count}");
        $this->command->info("  Hidden gems        : {$hiddenGems}");
        $this->command->info('✓========================================✓');
    }

    // ──────────────────────────────────────────────────────────────────────────
    // Helpers
    // ──────────────────────────────────────────────────────────────────────────

    private function determineRegion(string $country): string
    {
        $map = [
            'europe'      => ['France','Italy','Spain','Netherlands','Czech Republic','Austria','Portugal','Greece','Croatia','Hungary','Scotland','United Kingdom','Switzerland','Norway','Denmark','Sweden','Belgium','Estonia','Poland','Montenegro','Bosnia and Herzegovina','Slovenia','Iceland','Ireland','Germany','Finland','Albania','North Macedonia','Bulgaria','Romania','Serbia','Slovakia','Lithuania','Latvia','Luxembourg','Monaco','Andorra','Malta','Cyprus','Kosovo','Ukraine','Georgia'],
            'asia'        => ['Indonesia','Japan','Thailand','Vietnam','Cambodia','Laos','Malaysia','South Korea','Taiwan','Bhutan','India','Philippines','Sri Lanka','Nepal','Myanmar','Mongolia','China','Singapore','Brunei','East Timor','Maldives'],
            'middle_east' => ['Turkey','UAE','Jordan','Oman','Israel','Saudi Arabia','Egypt','Qatar','Bahrain','Kuwait','Lebanon','Syria','Iraq','Iran','Yemen','Palestine'],
            'africa'      => ['South Africa','Morocco','Tanzania','Kenya','Rwanda','Ethiopia','Zimbabwe','Botswana','Mauritius','Seychelles','Namibia','Madagascar','Tunisia','Algeria','Uganda','Ghana','Senegal','Mozambique','Zambia','Malawi','Mali'],
            'america'     => ['Peru','Brazil','Argentina','Colombia','Ecuador','Bolivia','Chile','Cuba','USA','Canada','Mexico','Costa Rica','Uruguay','Paraguay','Venezuela','Panama','Guatemala','Honduras','Nicaragua','El Salvador','Belize','Haiti','Dominican Republic','Jamaica','Barbados','Grenada','Saint Lucia','Antigua and Barbuda'],
            'oceania'     => ['Australia','New Zealand','French Polynesia','Fiji','Papua New Guinea','Samoa','Tonga','Vanuatu','Solomon Islands','New Caledonia','Palau','Micronesia'],
        ];

        foreach ($map as $region => $countries) {
            if (in_array($country, $countries)) return $region;
        }
        return 'general';
    }

    private function generateDescription(string $name, string $country): string
    {
        $templates = [
            "Discover the hidden charms of {$name}, {$country} — a destination that rewards the curious traveler with authentic experiences and unforgettable moments.",
            "Escape the crowds and explore {$name} in {$country}, where local traditions and natural beauty create the perfect off-the-beaten-path adventure.",
            "{$name}, {$country} awaits those seeking something different — a place where every corner reveals a new story and every interaction feels genuine.",
            "Step into the magic of {$name}, {$country} — a captivating destination that combines rich heritage with warm hospitality and stunning surroundings.",
            "Experience the undiscovered beauty of {$name}, {$country} — from breathtaking landscapes to vibrant local culture, this gem will steal your heart.",
        ];
        return $templates[array_rand($templates)];
    }

    /**
     * Picsum gives a stable, real photo for every destination based on its name.
     * No API key needed, never goes down, always returns a real image.
     */
    private function getPlaceholderImage(string $name): string
    {
        $seed = abs(crc32($name)) % 1000;
        return "https://picsum.photos/seed/{$seed}/600/400";
    }

    // ──────────────────────────────────────────────────────────────────────────
    // Data  [name, country, region, category, mood, price, description, image, badge, is_hidden_gem, match_score]
    // ──────────────────────────────────────────────────────────────────────────

    private function destinations(): array
    {
        return [
            // ── EUROPE ──────────────────────────────────────────────────────
            ['Paris','France','europe','historical','cultural',2400,
                'The city of light — Eiffel Tower, Louvre, Seine-side cafés, and the finest cuisine on Earth.',
                'https://images.unsplash.com/photo-1502602898657-3e91760cbb34?w=600&q=80',null,0,null],
            ['Rome','Italy','europe','historical','cultural',2000,
                'Eternal city of the Caesars — Colosseum, Vatican Museums, Trevi Fountain, and unbeatable pasta.',
                'https://images.unsplash.com/photo-1515542622106-078bda69e2d1?w=600&q=80',null,0,null],
            ['Barcelona','Spain','europe','food_culture','cultural',1900,
                'Gaudí\'s surreal architecture, La Rambla buzz, Barceloneta beach, and world-class tapas.',
                'https://images.unsplash.com/photo-1539037116277-4db20889f2d4?w=600&q=80','🔥 Trending',0,null],
            ['Amsterdam','Netherlands','europe','general','cultural',2100,
                'Golden-age canals, Rijksmuseum, cycling culture, and legendary nightlife.',
                'https://images.unsplash.com/photo-1534351590666-13e3e96b5017?w=600&q=80',null,0,null],
            ['Prague','Czech Republic','europe','historical','romantic',1400,
                'Fairy-tale skyline of Gothic spires and Baroque domes above a perfectly preserved medieval old town.',
                'https://images.unsplash.com/photo-1592906209472-a36b1f3782ef?w=600&q=80',null,0,null],
            ['Vienna','Austria','europe','historical','cultural',2200,
                'Imperial palaces, grand opera houses, Sachertorte, and Europe\'s most refined café culture.',
                'https://images.unsplash.com/photo-1516550135131-fe3dcaa57db7?w=600&q=80',null,0,null],
            ['Lisbon','Portugal','europe','trending','cultural',1700,
                'Pastel hilltop neighbourhoods, vintage trams, fado music, and Atlantic seafood at every corner.',
                'https://images.unsplash.com/photo-1558370781-d6196591e1f5?w=600&q=80','🔥 Trending',0,null],
            ['Santorini','Greece','europe','beach','romantic',2800,
                'Iconic blue-domed churches, volcanic caldera views, and the most dramatic sunsets on Earth.',
                'https://images.unsplash.com/photo-1570077188670-e3a8d69ac5ff?w=600&q=80','💝 Romantic',0,null],
            ['Athens','Greece','europe','historical','cultural',1600,
                'Cradle of Western civilisation — the Acropolis, Parthenon, and vibrant Monastiraki square.',
                'https://images.unsplash.com/photo-1555993539-1732b0258235?w=600&q=80','🏛️ Historic',0,null],
            ['Dubrovnik','Croatia','europe','beach','romantic',2100,
                'Pearl of the Adriatic — luminous white city walls, jade-green sea, and medieval charm.',
                'https://images.unsplash.com/photo-1555990538-c4c4b8e2a0a6?w=600&q=80',null,0,null],
            ['Budapest','Hungary','europe','historical','romantic',1300,
                'Thermal baths, ruin bars, and the majestic parliament straddling the glittering Danube.',
                'https://images.unsplash.com/photo-1516912481808-3406841bd33c?w=600&q=80','💝 Romantic',0,null],
            ['Edinburgh','Scotland','europe','historical','cultural',1800,
                'Dramatic castle on volcanic rock, whisky heritage, Arthur\'s Seat, and the Fringe Festival.',
                'https://images.unsplash.com/photo-1562612532-c5e0c9b8e26e?w=600&q=80','🏛️ Historic',0,null],
            ['London','United Kingdom','europe','historical','cultural',2600,
                'Thames, Tower Bridge, British Museum, West End theatre, and the world\'s most cosmopolitan energy.',
                'https://images.unsplash.com/photo-1513635269975-59663e0ac1ad?w=600&q=80',null,0,null],
            ['Interlaken','Switzerland','europe','mountain','adventurous',3200,
                'Adventure capital of the Alps — skydiving, paragliding, and skiing beneath the Jungfrau.',
                'https://images.unsplash.com/photo-1531366936337-7c912a4589a7?w=600&q=80','🏔️ Adventure',0,null],
            ['Florence','Italy','europe','historical','cultural',2100,
                'Birthplace of the Renaissance — Michelangelo\'s David, Botticelli\'s Venus, and Tuscan wine.',
                'https://images.unsplash.com/photo-1541370976299-4d24ebbc9077?w=600&q=80','🏛️ Historic',0,null],
            ['Venice','Italy','europe','romantic','romantic',2600,
                'Floating city of canals, gondolas, masked carnival, and baroque grandeur unlike anywhere else.',
                'https://images.unsplash.com/photo-1523906834658-6e24ef2386f9?w=600&q=80','💝 Romantic',0,null],
            ['Amalfi Coast','Italy','europe','beach','romantic',3000,
                'Clifftop villages cascading into turquoise Mediterranean water on Italy\'s most breathtaking coastline.',
                'https://images.unsplash.com/photo-1530841377377-3ff06c0ca713?w=600&q=80',null,0,null],
            ['Cinque Terre','Italy','europe','beach','relaxed',2200,
                'Five pastel fishing villages clinging to dramatic Ligurian sea cliffs — car-free perfection.',
                'https://images.unsplash.com/photo-1499678329028-101435549a4e?w=600&q=80',null,0,null],
            ['Reykjavik','Iceland','europe','eco_tourism','adventurous',3500,
                'Gateway to the northern lights, midnight sun, geysers, and the world\'s most dramatic volcanic scenery.',
                'https://images.unsplash.com/photo-1476610182048-b716b8518aae?w=600&q=80',null,0,null],
            ['Bergen','Norway','europe','mountain','adventurous',2800,
                'Gateway to the Norwegian fjords — colourful Bryggen wharf, funicular views, and fresh seafood.',
                'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=600&q=80',null,0,null],
            ['Copenhagen','Denmark','europe','food_culture','cultural',2600,
                'New Nordic cuisine, Tivoli Gardens, Nyhavn canal houses, and cycling culture.',
                'https://images.unsplash.com/photo-1513622470522-26c3c8a854bc?w=600&q=80',null,0,null],
            ['Stockholm','Sweden','europe','historical','cultural',2500,
                'City of fourteen islands — Nobel Museum, Vasa warship, and Gamla Stan old town.',
                'https://images.unsplash.com/photo-1509356843151-3e7d96241e11?w=600&q=80',null,0,null],
            ['Porto','Portugal','europe','food_culture','cultural',1500,
                'Medieval Ribeira, port wine cellars, azulejo tile facades, and the Douro Valley nearby.',
                'https://images.unsplash.com/photo-1555881400-74d7acaacd8b?w=600&q=80',null,0,null],
            ['Seville','Spain','europe','historical','cultural',1700,
                'Flamenco birthplace, Moorish Alcázar palace, and orange-blossom streets in Andalusia\'s capital.',
                'https://images.unsplash.com/photo-1549144511-f099e773c147?w=600&q=80',null,0,null],
            ['Granada','Spain','europe','historical','cultural',1600,
                'The legendary Alhambra palace crowns this Moorish gem at the foot of the Sierra Nevada.',
                'https://images.unsplash.com/photo-1501786223405-6d024d7c3b8d?w=600&q=80',null,0,null],
            ['Bruges','Belgium','europe','romantic','cultural',1900,
                'Venice of the North — medieval canals, lace workshops, chocolate shops, and Gothic belfry.',
                'https://images.unsplash.com/photo-1491557345352-5929e343eb89?w=600&q=80','💝 Romantic',0,null],
            ['Tallinn','Estonia','europe','historical','cultural',1400,
                'Perfectly preserved medieval old town with cobbled lanes, limestone towers, and digital innovation.',
                'https://images.unsplash.com/photo-1562952083-5b944bfc6a9e?w=600&q=80','⭐ AI Pick',0,null],
            ['Krakow','Poland','europe','historical','cultural',1200,
                'Royal Wawel Castle, harrowing Auschwitz memorial nearby, and an unbeatable medieval city square.',
                'https://images.unsplash.com/photo-1574877593654-5fac3e0a5d80?w=600&q=80',null,0,null],
            ['Salzburg','Austria','europe','historical','cultural',2300,
                'Mozart\'s birthplace, Hohensalzburg fortress, Sound of Music hills, and stunning Alpine backdrop.',
                'https://images.unsplash.com/photo-1575510413800-5b99f87da5e1?w=600&q=80',null,0,null],
            ['Berlin','Germany','europe','historical','cultural',2000,
                'Capital of cool — Wall history, world-class museums, legendary nightlife, and reinvention.',
                'https://images.unsplash.com/photo-1560969184-10fe8719e047?w=600&q=80',null,0,null],
            ['Munich','Germany','europe','food_culture','cultural',2200,
                'Oktoberfest, beer gardens, BMW museum, and the Bavarian Alps at your doorstep.',
                'https://images.unsplash.com/photo-1595867818082-083862f3d630?w=600&q=80',null,0,null],
            ['Hamburg','Germany','europe','general','cultural',1900,
                'Germany\'s gateway to the world — Speicherstadt, Elbphilharmonie, and Reeperbahn nights.',
                'https://images.unsplash.com/photo-1553452118-621e1c86066b?w=600&q=80',null,0,null],
            ['Dublin','Ireland','europe','food_culture','cultural',2100,
                'Craic agus ceol — Guinness, Trinity College, Georgian doors, and Irish warmth.',
                'https://images.unsplash.com/photo-1549918864-48ac978761a4?w=600&q=80',null,0,null],
            ['Helsinki','Finland','europe','general','cultural',2300,
                'Design capital, island fortresses, sauna culture, and gateway to the archipelago.',
                'https://images.unsplash.com/photo-1559675264-d7f2c7e9f5c9?w=600&q=80',null,0,null],
            ['Warsaw','Poland','europe','historical','cultural',1100,
                'Phoenix city — reconstructed Old Town, poignant history, and vibrant modern energy.',
                'https://images.unsplash.com/photo-1575637508295-3c4176d8a9d4?w=600&q=80',null,0,null],
            // Hidden Gems — Europe
            ['Hallstatt','Austria','europe','mountain','romantic',2800,
                'Fairy-tale lakeside village in the Salzkammergut that inspired a thousand postcards.',
                'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=600&q=80','💝 Romantic',1,96],
            ['Cesky Krumlov','Czech Republic','europe','historical','cultural',1200,
                'Perfectly preserved Renaissance town coiled around a bend in the Vltava River.',
                'https://images.unsplash.com/photo-1590086782957-93c06ef21604?w=600&q=80',null,1,93],
            ['Sintra','Portugal','europe','historical','romantic',1800,
                'Colourful palaces perched on forested hilltops above the Atlantic — a UNESCO wonderland.',
                'https://images.unsplash.com/photo-1555881400-74d7acaacd8b?w=600&q=80',null,1,91],
            ['Kotor','Montenegro','europe','historical','cultural',1100,
                'Dramatic medieval walled city at the foot of Mount Lovćen beside the Adriatic Sea.',
                'https://images.unsplash.com/photo-1605289982774-9a6fef564df8?w=600&q=80',null,1,94],
            ['Mostar','Bosnia and Herzegovina','europe','historical','cultural',1000,
                'The iconic Stari Most bridge arching over the Neretva River — a symbol of resilience and hope.',
                'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&q=80',null,1,89],
            ['Ljubljana','Slovenia','europe','general','cultural',1400,
                'Compact, walkable capital with a picturesque castle, open-air market, and café-lined riverbank.',
                'https://images.unsplash.com/photo-1549895950-e5b1f6f90c9d?w=600&q=80',null,1,87],
            ['Plitvice Lakes','Croatia','europe','eco_tourism','eco',1700,
                'Cascading terraced lakes and waterfalls in a UNESCO national park of otherworldly beauty.',
                'https://images.unsplash.com/photo-1558618047-f4e80e55e16b?w=600&q=80','🌿 Eco',1,95],
            ['Meteora','Greece','europe','historical','adventurous',1900,
                'Ancient monasteries perched impossibly atop dramatic sandstone pillars in central Thessaly.',
                'https://images.unsplash.com/photo-1524231757912-21f4fe3a7200?w=600&q=80',null,1,92],
            ['Faroe Islands','Denmark','europe','eco_tourism','adventurous',3200,
                'Remote North Atlantic archipelago of dramatic sea cliffs, waterfalls, and Viking heritage.',
                'https://images.unsplash.com/photo-1504701954957-2010ec3bcec1?w=600&q=80','🌿 Eco',1,93],
            ['Ghent','Belgium','europe','historical','cultural',1600,
                'Underrated Flemish gem with three medieval towers, vibrant student life, and world-class beer.',
                'https://images.unsplash.com/photo-1491557345352-5929e343eb89?w=600&q=80',null,1,88],
            ['Madeira','Portugal','europe','eco_tourism','adventurous',2000,
                'Atlantic island of dramatic volcanic landscapes, levada walks, and exotic botanical gardens.',
                'https://images.unsplash.com/photo-1556741533-6e50e5b7c7e0?w=600&q=80',null,1,90],
            ['Tbilisi','Georgia','europe','trending','cultural',700,
                'Caucasus gem — sulphur baths, eclectic architecture, and legendary supra feasts.',
                'https://images.unsplash.com/photo-1589156191108-c762ff4b96ab?w=600&q=80','🔥 Up & Coming',1,96],
            ['Svaneti','Georgia','europe','mountain','adventurous',800,
                'Tower-studded villages in the highest Caucasus — Europe\'s most remote mountain region.',
                'https://images.unsplash.com/photo-1589156191108-c762ff4b96ab?w=600&q=80','🏔️ Remote Peaks',1,97],
            ['Lofoten Islands','Norway','europe','mountain','adventurous',2800,
                'Dramatic peaks rising from Arctic Ocean — fishing villages, northern lights, and midnight sun.',
                'https://images.unsplash.com/photo-1504701954957-2010ec3bcec1?w=600&q=80','🏔️ Arctic Beauty',1,98],
            ['Svalbard','Norway','europe','eco_tourism','adventurous',4000,
                'Arctic wilderness — polar bears, glaciers, and midnight sun at 78° north.',
                'https://images.unsplash.com/photo-1476610182048-b716b8518aae?w=600&q=80','❄️ Arctic Frontier',1,97],
            ['Plovdiv','Bulgaria','europe','historical','cultural',550,
                'Europe\'s oldest continually inhabited city — Roman theatre, revival houses, and creative quarter.',
                'https://images.unsplash.com/photo-1605289982774-9a6fef564df8?w=600&q=80','🏛️ Ancient Gem',1,94],
            ['Sighișoara','Romania','europe','historical','cultural',550,
                'Birthplace of Dracula — perfectly preserved medieval citadel with colourful houses.',
                'https://images.unsplash.com/photo-1605289982774-9a6fef564df8?w=600&q=80','🧛 Transylvanian Gem',1,95],
            ['Brasov','Romania','europe','mountain','adventurous',600,
                'Gateway to Transylvania — Gothic Black Church, surrounding Carpathians, and nearby Bran Castle.',
                'https://images.unsplash.com/photo-1605289982774-9a6fef564df8?w=600&q=80','🏔️ Carpathian Gateway',1,92],
            ['Maramureș','Romania','europe','eco_tourism','cultural',550,
                'Living museum — wooden churches, horse-drawn carts, and Europe\'s most traditional villages.',
                'https://images.unsplash.com/photo-1605289982774-9a6fef564df8?w=600&q=80','🌿 Living Tradition',1,96],
            ['Visby','Sweden','europe','historical','cultural',700,
                'Hanseatic gem on Gotland — 13th-century city wall, rose gardens, and medieval ruins.',
                'https://images.unsplash.com/photo-1509356843151-3e7d96241e11?w=600&q=80','🌹 Rose City',1,94],
            ['Ohrid','North Macedonia','europe','historical','cultural',600,
                'Balkan Jerusalem — 365 churches, ancient lake, and UNESCO treasures without crowds.',
                'https://images.unsplash.com/photo-1605289982774-9a6fef564df8?w=600&q=80','💎 Hidden Gem',1,95],
            ['Berat','Albania','europe','historical','cultural',500,
                'City of a Thousand Windows — Ottoman houses cascading down hillside, castle still inhabited.',
                'https://images.unsplash.com/photo-1605289982774-9a6fef564df8?w=600&q=80','🏛️ UNESCO Gem',1,94],
            ['Theth','Albania','europe','mountain','adventurous',350,
                'Isolated mountain village — stone towers, crystal rivers, and Albanian Alps.',
                'https://images.unsplash.com/photo-1605289982774-9a6fef564df8?w=600&q=80','🏔️ Accursed Mountains',1,96],
            ['Prizren','Kosovo','europe','historical','cultural',400,
                'Ottoman-era gem — fortress views, stone bridge, and Balkan hospitality.',
                'https://images.unsplash.com/photo-1605289982774-9a6fef564df8?w=600&q=80','🏛️ Kosovo Gem',1,92],
            ['Korčula','Croatia','europe','historical','cultural',700,
                'Mini Dubrovnik — alleged birthplace of Marco Polo, dense forests, and wine.',
                'https://images.unsplash.com/photo-1555990538-c4c4b8e2a0a6?w=600&q=80','🌳 Marco Polo',1,91],
            ['Vis','Croatia','europe','beach','relaxed',800,
                'Remote island — Stiniva Cove, military history, and Blue Cave.',
                'https://images.unsplash.com/photo-1555990538-c4c4b8e2a0a6?w=600&q=80','💙 Blue Cave',1,93],
            ['Jajce','Bosnia and Herzegovina','europe','historical','cultural',350,
                'Waterfall in the city centre, AVNOJ museum, and medieval fortress.',
                'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&q=80','💧 City Waterfall',1,91],
            ['Blagaj','Bosnia and Herzegovina','europe','historical','cultural',350,
                'Dervish monastery at the Buna River spring — cliffside serenity and beauty.',
                'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&q=80','⛲ Spring Monastery',1,94],
            ['Lviv','Ukraine','europe','food_culture','cultural',500,
                'Coffee, chocolate, and cobblestones — Austria-Hungary\'s most charming easternmost city.',
                'https://images.unsplash.com/photo-1574877593654-5fac3e0a5d80?w=600&q=80','☕ Coffee Capital',1,95],
            // ── ASIA ────────────────────────────────────────────────────────
            ['Bali','Indonesia','asia','trending','relaxed',1200,
                'Spiritual Indonesia — rice terraces, Hindu temples, surf beaches, and world-class wellness retreats.',
                'https://images.unsplash.com/photo-1537953773345-d172ccf13cf1?w=600&q=80','🔥 Trending',0,null],
            ['Kyoto','Japan','asia','ai_pick','cultural',2100,
                'Ancient Japan — 1,600 Buddhist temples, geisha districts, bamboo groves, and tea ceremony.',
                'https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=600&q=80','⭐ AI Pick',0,null],
            ['Tokyo','Japan','asia','food_culture','cultural',2400,
                'World\'s most exciting megacity — neon-lit Shibuya, sushi at dawn, and flawless technology.',
                'https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=600&q=80',null,0,null],
            ['Bangkok','Thailand','asia','food_culture','foodie',900,
                'Tuk-tuks, night markets, golden wats, and the world\'s best street food in Thailand\'s capital.',
                'https://images.unsplash.com/photo-1508009603885-50cf7c579365?w=600&q=80','🍜 Foodie',0,null],
            ['Maldives','Maldives','asia','beach','relaxed',3500,
                'Overwater villas, neon coral reefs, and the world\'s most luminous turquoise lagoons.',
                'https://images.unsplash.com/photo-1514282401047-d79a71a590e8?w=600&q=80','🌊 Beach',0,null],
            ['Siem Reap','Cambodia','asia','historical','cultural',900,
                'Gateway to Angkor Wat — the world\'s largest religious monument and pinnacle of Khmer civilisation.',
                'https://images.unsplash.com/photo-1564596823821-79b19bce8f8e?w=600&q=80','🏛️ Historic',0,null],
            ['Singapore','Singapore','asia','food_culture','foodie',2200,
                'Futuristic city-state of Gardens by the Bay, hawker centres, and seamless multicultural dining.',
                'https://images.unsplash.com/photo-1525625293386-3f8f99389edd?w=600&q=80','🍜 Foodie',0,null],
            ['Seoul','South Korea','asia','food_culture','cultural',1800,
                'K-culture capital — Gyeongbokgung palace, Dongdaemun market, bibimbap, and cutting-edge tech.',
                'https://images.unsplash.com/photo-1538485399081-7191377e8241?w=600&q=80',null,0,null],
            ['Jaipur','India','asia','historical','cultural',900,
                'Pink City of magnificent forts, Hawa Mahal, Amber Palace, and vibrant bazaars in Rajasthan.',
                'https://images.unsplash.com/photo-1477587458883-47145ed6cecc?w=600&q=80','🏛️ Historic',0,null],
            ['Varanasi','India','asia','historical','cultural',800,
                'World\'s oldest living city — Ganges ghats, dawn aarti ceremonies, and the rhythm of Hindu life.',
                'https://images.unsplash.com/photo-1561361058-c24cecae35ca?w=600&q=80',null,0,null],
            ['Kerala','India','asia','eco_tourism','relaxed',1100,
                'God\'s Own Country — backwater houseboat cruises, Ayurveda retreats, and spice plantation treks.',
                'https://images.unsplash.com/photo-1593693397690-362cb9666fc2?w=600&q=80','🌿 Eco',0,null],
            ['Goa','India','asia','beach','relaxed',900,
                'India\'s party coast — Portuguese churches, cashew feni, spice markets, and palm-fringed beaches.',
                'https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?w=600&q=80',null,0,null],
            ['Osaka','Japan','asia','food_culture','foodie',2000,
                'Japan\'s kitchen — takoyaki, ramen, Dotonbori neon, and the most welcoming locals in the country.',
                'https://images.unsplash.com/photo-1590559899731-a382839e5549?w=600&q=80','🍜 Foodie',0,null],
            ['Taipei','Taiwan','asia','food_culture','foodie',1400,
                'Safe, friendly, and delicious — night markets, Jiufen old street, and the best bubble tea on Earth.',
                'https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=600&q=80','🍜 Foodie',0,null],
            ['Ha Long Bay','Vietnam','asia','eco_tourism','adventurous',1200,
                'Thousands of limestone karst pillars rising from emerald waters in a UNESCO World Heritage seascape.',
                'https://images.unsplash.com/photo-1528360983277-13d401cdc186?w=600&q=80','🌿 Eco',0,null],
            ['Cappadocia','Turkey','middle_east','adventurous','adventurous',1800,
                'Fairy chimneys, underground cities, and the world\'s most iconic hot-air balloon rides.',
                'https://images.unsplash.com/photo-1565010928590-0c83c68df65c?w=600&q=80','🏔️ Adventure',0,null],
            ['Istanbul','Turkey','middle_east','historical','cultural',1700,
                'Where Europe meets Asia — the Blue Mosque, Grand Bazaar, and Bosphorus in one extraordinary city.',
                'https://images.unsplash.com/photo-1524231757912-21f4fe3a7200?w=600&q=80',null,0,null],
            // Hidden gems — Asia
            ['Chiang Mai','Thailand','asia','eco_tourism','cultural',750,
                'Northern Thai gem of 300 temples, ethical elephant sanctuaries, and night bazaars.',
                'https://images.unsplash.com/photo-1528360983277-13d401cdc186?w=600&q=80',null,1,91],
            ['Hoi An','Vietnam','asia','historical','cultural',700,
                'Lantern-lit Ancient Town UNESCO site where Japanese merchant houses meet French colonial cafés.',
                'https://images.unsplash.com/photo-1528127269322-539801943592?w=600&q=80',null,1,86],
            ['Luang Prabang','Laos','asia','general','relaxed',800,
                'Sacred Mekong city of gilded temples, saffron-robed monks at dawn, and jungle waterfalls nearby.',
                'https://images.unsplash.com/photo-1552465011-b4e21bf6e79a?w=600&q=80',null,1,90],
            ['Ubud','Indonesia','asia','eco_tourism','relaxed',1100,
                'Cultural heart of Bali — rice terraces, artists\' studios, yoga retreats, and jungle walks.',
                'https://images.unsplash.com/photo-1555400038-63f5ba517a47?w=600&q=80','🌿 Eco',0,null],
            ['Komodo','Indonesia','asia','eco_tourism','adventurous',1400,
                'Dragon lizards, pink-sand beaches, and world-class diving in the remote Flores Sea archipelago.',
                'https://images.unsplash.com/photo-1568454537842-d933259bb258?w=600&q=80','🌿 Eco',1,94],
            ['Penang','Malaysia','asia','food_culture','foodie',900,
                'UNESCO George Town of street art, Peranakan shophouses, and Asia\'s most celebrated street food.',
                'https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=600&q=80','🍜 Foodie',1,92],
            ['Bhutan','Bhutan','asia','eco_tourism','cultural',3500,
                'Last Shangri-La — carbon-negative Himalayan kingdom of Tiger\'s Nest monastery and happiness index.',
                'https://images.unsplash.com/photo-1548013146-72479768bada?w=600&q=80','🌿 Eco',1,96],
            ['Udaipur','India','asia','romantic','romantic',1000,
                'City of Lakes — Lake Palace shimmering on the water, ornate havelis, and Rajasthani romance.',
                'https://images.unsplash.com/photo-1524492412937-b28074a5d7da?w=600&q=80','💝 Romantic',1,93],
            ['Hokkaido','Japan','asia','mountain','adventurous',2200,
                'Japan\'s northern frontier — powder-snow skiing, lavender fields, seafood, and brown bears.',
                'https://images.unsplash.com/photo-1542640244-7e672d6cef4e?w=600&q=80',null,0,null],
            ['Kanazawa','Japan','asia','historical','cultural',1600,
                'Little Kyoto — geisha districts, samurai quarters, and Kenrokuen Garden.',
                'https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=600&q=80','🍂 Autumn Splendor',1,95],
            ['Naoshima','Japan','asia','trending','cultural',1500,
                'Art island — world-class contemporary art museums in the Seto Inland Sea.',
                'https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=600&q=80','🎨 Art Island',1,96],
            ['Palawan','Philippines','asia','beach','relaxed',700,
                'Last frontier — underground river, lagoons of El Nido, and island-hopping paradise.',
                'https://images.unsplash.com/photo-1579591919791-0e3737ae3808?w=600&q=80','🏝️ Last Frontier',1,96],
            ['Raja Ampat','Indonesia','asia','eco_tourism','adventurous',1500,
                'Epicenter of marine biodiversity — the world\'s best diving and remote island beauty.',
                'https://images.unsplash.com/photo-1555400038-63f5ba517a47?w=600&q=80','🐠 Diving Paradise',1,97],
            ['Ninh Binh','Vietnam','asia','eco_tourism','adventurous',500,
                'Ha Long Bay on land — karst peaks, rice paddies, and boat rides through cave temples.',
                'https://images.unsplash.com/photo-1528360983277-13d401cdc186?w=600&q=80','🏞️ Inland Bay',1,95],
            ['Phong Nha','Vietnam','asia','eco_tourism','adventurous',600,
                'Cave kingdom — world\'s largest cave Son Doong, Paradise Cave, and jungle trekking.',
                'https://images.unsplash.com/photo-1528360983277-13d401cdc186?w=600&q=80','🕳️ Cave Kingdom',1,96],
            ['Inle Lake','Myanmar','asia','eco_tourism','cultural',450,
                'Leg-rowing fishermen, floating gardens, and stilted villages on a vast mountain lake.',
                'https://images.unsplash.com/photo-1564596823821-79b19bce8f8e?w=600&q=80','🚣 Floating Life',1,95],
            ['Yogyakarta','Indonesia','asia','historical','cultural',600,
                'Java\'s cultural soul — Borobudur, Prambanan, and batik traditions.',
                'https://images.unsplash.com/photo-1555400038-63f5ba517a47?w=600&q=80','🎭 Javanese Heart',1,93],
            ['Jeju Island','South Korea','asia','eco_tourism','relaxed',1300,
                'Korean Hawaii — volcanic landscapes, Hallasan mountain, and haenyeo divers.',
                'https://images.unsplash.com/photo-1538485399081-7191377e8241?w=600&q=80','🌋 Volcanic Island',1,93],
            // ── MIDDLE EAST ─────────────────────────────────────────────────
            ['Dubai','UAE','middle_east','general','relaxed',2800,
                'Burj Khalifa, desert safaris, gold souk, and ultra-luxury in the world\'s most ambitious city.',
                'https://images.unsplash.com/photo-1512453979798-5ea266f8880c?w=600&q=80',null,0,null],
            ['Petra','Jordan','middle_east','historical','adventurous',1600,
                'Rose-red city carved from sandstone cliffs — the Treasury facade is one of the world\'s greatest sights.',
                'https://images.unsplash.com/photo-1539650116574-75c0c6d73c0e?w=600&q=80','🏛️ Historic',0,null],
            ['Muscat','Oman','middle_east','general','cultural',1500,
                'Graceful Arabian Gulf capital of Sultan Qaboos Grand Mosque, corniche, and friendly souks.',
                'https://images.unsplash.com/photo-1586861635167-e5223aadc9fe?w=600&q=80',null,0,null],
            ['Jerusalem','Israel','middle_east','historical','cultural',1800,
                'Three-faith holy city — Western Wall, Church of Holy Sepulchre, and Dome of the Rock in one square mile.',
                'https://images.unsplash.com/photo-1544948047-5a1db8b29c5a?w=600&q=80','🏛️ Historic',0,null],
            ['Luxor','Egypt','middle_east','historical','cultural',1200,
                'Greatest open-air museum on Earth — Valley of the Kings, Karnak Temple, and Nile felucca rides.',
                'https://images.unsplash.com/photo-1539650116574-75c0c6d73c0e?w=600&q=80','🏛️ Historic',0,null],
            ['Cairo','Egypt','middle_east','historical','cultural',1100,
                'Great Pyramid, Sphinx, Egyptian Museum, and the glorious energy of 20 million people.',
                'https://images.unsplash.com/photo-1553913861-c0fddf2619ee?w=600&q=80',null,0,null],
            // Hidden gems — Middle East
            ['Wadi Rum','Jordan','middle_east','eco_tourism','adventurous',1400,
                'Mars-like desert of monolithic rock formations, Bedouin camps, and star-filled skies.',
                'https://images.unsplash.com/photo-1538969867081-5f4e5e3c7b2a?w=600&q=80','🌿 Eco',1,92],
            ['AlUla','Saudi Arabia','middle_east','historical','adventurous',2000,
                'Saudi Arabia\'s hidden wonder — Hegra Nabataean tombs, rose-red canyons, and luxury desert eco-lodges.',
                'https://images.unsplash.com/photo-1586861635167-e5223aadc9fe?w=600&q=80','⭐ AI Pick',1,94],
            ['Socotra','Yemen','middle_east','eco_tourism','adventurous',3500,
                'Alien island — dragon blood trees, bottle trees, and 30% endemic species.',
                'https://images.unsplash.com/photo-1586861635167-e5223aadc9fe?w=600&q=80','🌳 Alien Island',1,98],
            ['Shiraz','Iran','middle_east','historical','cultural',700,
                'City of poets, gardens, and the jewel-like Nasir al-Mulk Pink Mosque.',
                'https://images.unsplash.com/photo-1586861635167-e5223aadc9fe?w=600&q=80','🌸 Persian Gardens',1,94],
            ['Yazd','Iran','middle_east','historical','cultural',650,
                'Desert city of windcatchers — Zoroastrian heritage and labyrinthine lanes.',
                'https://images.unsplash.com/photo-1586861635167-e5223aadc9fe?w=600&q=80','🌬️ Windcatcher City',1,95],
            ['Salalah','Oman','middle_east','eco_tourism','relaxed',1000,
                'Arabian Peninsula\'s greenest corner — monsoon season transforms desert to lush jungle.',
                'https://images.unsplash.com/photo-1586861635167-e5223aadc9fe?w=600&q=80','🌧️ Green Oman',1,94],
            // ── AFRICA ──────────────────────────────────────────────────────
            ['Cape Town','South Africa','africa','trending','adventurous',1600,
                'Table Mountain, Cape Peninsula, Boulders penguin beach, and winelands all within an hour.',
                'https://images.unsplash.com/photo-1580060839134-75a5edca2e99?w=600&q=80','🔥 Trending',0,null],
            ['Marrakech','Morocco','africa','historical','cultural',1300,
                'Labyrinthine medina, Djemaa el-Fna square, hammams, souks, and Atlas Mountains nearby.',
                'https://images.unsplash.com/photo-1597211684565-dca64d72bdfe?w=600&q=80',null,0,null],
            ['Zanzibar','Tanzania','africa','beach','relaxed',1500,
                'Spice Island of pristine white beaches, Stone Town UNESCO old town, and technicolour coral reefs.',
                'https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=600&q=80','🌊 Beach',0,null],
            ['Serengeti','Tanzania','africa','eco_tourism','adventurous',3500,
                'Greatest wildlife spectacle on Earth — the Great Migration of two million wildebeest.',
                'https://images.unsplash.com/photo-1516426122078-c23e76319801?w=600&q=80','🌿 Eco',0,null],
            ['Masai Mara','Kenya','africa','eco_tourism','adventurous',3400,
                'Kenya\'s finest savannah — lions at dusk, hot-air balloon safaris, and Maasai culture.',
                'https://images.unsplash.com/photo-1547471080-7cc2caa01a7e?w=600&q=80','🌿 Eco',0,null],
            ['Mauritius','Mauritius','africa','beach','romantic',2800,
                'Indian Ocean jewel of turquoise lagoons, sugar-cane hills, and barefoot luxury resorts.',
                'https://images.unsplash.com/photo-1589979481223-deb893043163?w=600&q=80','💝 Romantic',0,null],
            ['Seychelles','Seychelles','africa','beach','relaxed',3800,
                'Extraordinary granite boulders on powder-white beaches with sea turtles and crystal warm water.',
                'https://images.unsplash.com/photo-1573843981267-be1999ff37cd?w=600&q=80',null,0,null],
            ['Victoria Falls','Zimbabwe','africa','eco_tourism','adventurous',2000,
                'The Smoke that Thunders — world\'s largest waterfall on the Zambezi, plus white-water rafting.',
                'https://images.unsplash.com/photo-1516426122078-c23e76319801?w=600&q=80','🌿 Eco',0,null],
            // Hidden gems — Africa
            ['Chefchaouen','Morocco','africa','general','relaxed',900,
                'The Blue Pearl — mountain village painted entirely in blue, perfect for peaceful wandering.',
                'https://images.unsplash.com/photo-1548699894-68e1ad8c34bc?w=600&q=80','⭐ AI Pick',1,93],
            ['Rwanda - Volcanoes','Rwanda','africa','eco_tourism','adventurous',4000,
                'Mountain gorilla trekking in mist-shrouded Virunga volcanoes — a life-changing encounter.',
                'https://images.unsplash.com/photo-1590523741831-ab7e8b8f9c7f?w=600&q=80','🌿 Eco',1,97],
            ['Lalibela','Ethiopia','africa','historical','cultural',1400,
                'Eleven rock-hewn Orthodox churches cut from living stone — Ethiopia\'s New Jerusalem.',
                'https://images.unsplash.com/photo-1539650116574-75c0c6d73c0e?w=600&q=80','🏛️ Historic',1,95],
            ['Okavango Delta','Botswana','africa','eco_tourism','adventurous',4500,
                'World\'s largest inland delta — mokoro canoe safaris, elephant herds, and luxury tented camps.',
                'https://images.unsplash.com/photo-1547471080-7cc2caa01a7e?w=600&q=80','🌿 Eco',1,96],
            ['Namibia - Sossusvlei','Namibia','africa','eco_tourism','adventurous',2400,
                'Earth\'s oldest desert — towering red dunes, Dead Vlei trees, and the undimmed Milky Way.',
                'https://images.unsplash.com/photo-1509316785289-025f5b846b35?w=600&q=80','🌿 Eco',1,93],
            ['Fez','Morocco','africa','historical','cultural',1100,
                'World\'s best-preserved medieval Islamic city — leather tanneries, madrasas, and ancient souks.',
                'https://images.unsplash.com/photo-1572803534682-1cc10d813bc1?w=600&q=80',null,1,91],
            ['Madagascar','Morocco','africa','eco_tourism','adventurous',2000,
                '90% endemic wildlife — ring-tailed lemurs, baobab avenues, and alien limestone tsingy.',
                'https://images.unsplash.com/photo-1590523741831-ab7e8b8f9c7f?w=600&q=80','🌿 Eco',1,94],
            ['Lamu','Kenya','africa','historical','cultural',1200,
                'Swahili jewel — no cars, donkey transport, and 500 years of unbroken culture.',
                'https://images.unsplash.com/photo-1547471080-7cc2caa01a7e?w=600&q=80','🏝️ Swahili Gem',1,96],
            ['Timbuktu','Mali','africa','historical','cultural',1200,
                'Legendary desert crossroads — ancient manuscripts and the heart of Saharan mystique.',
                'https://images.unsplash.com/photo-1547471080-7cc2caa01a7e?w=600&q=80','📜 Legendary City',1,95],
            ['Quirimbas','Mozambique','africa','beach','relaxed',1500,
                'Remote archipelago — untouched coral, dhow safaris, and barefoot luxury.',
                'https://images.unsplash.com/photo-1547471080-7cc2caa01a7e?w=600&q=80','⛵ Dhow Paradise',1,94],
            // ── AMERICAS ────────────────────────────────────────────────────
            ['Machu Picchu','Peru','america','historical','adventurous',2200,
                'Lost city of the Incas perched among cloud-forest peaks on the Urubamba River — a global icon.',
                'https://images.unsplash.com/photo-1526392060635-9d6019884377?w=600&q=80','🏛️ Historic',0,null],
            ['Rio de Janeiro','Brazil','america','trending','relaxed',1900,
                'Carnival, Christ the Redeemer, Copacabana, and the most exuberant city on the planet.',
                'https://images.unsplash.com/photo-1483729558449-99ef09a8c325?w=600&q=80','🔥 Trending',0,null],
            ['Buenos Aires','Argentina','america','food_culture','cultural',1600,
                'Paris of South America — tango, steak, Recoleta cemetery, and passionate football culture.',
                'https://images.unsplash.com/photo-1589909202802-8f4aadce1849?w=600&q=80',null,0,null],
            ['Cartagena','Colombia','america','historical','romantic',1400,
                'Walled Caribbean city of bougainvillea-draped colonial mansions, salsa music, and crystal sea.',
                'https://images.unsplash.com/photo-1597976836977-6e1a0e6e6c87?w=600&q=80','💝 Romantic',0,null],
            ['Galápagos Islands','Ecuador','america','eco_tourism','adventurous',4000,
                'Darwin\'s inspiration — sea lions, iguanas, and tortoises evolved in isolation on volcanic islands.',
                'https://images.unsplash.com/photo-1548199973-03cce0bbc87b?w=600&q=80','🌿 Eco',0,null],
            ['Havana','Cuba','america','historical','cultural',1400,
                'Frozen-in-time capital of vintage cars, salsa beats, colonial architecture, and rum at every corner.',
                'https://images.unsplash.com/photo-1519451241324-20b4ea2c4220?w=600&q=80',null,0,null],
            ['New York','USA','america','general','cultural',2800,
                'The city that never sleeps — Times Square, Central Park, world-class museums, and the finest dining.',
                'https://images.unsplash.com/photo-1496442226666-8d4d0e62e6e9?w=600&q=80',null,0,null],
            ['New Orleans','USA','america','food_culture','foodie',1800,
                'Jazz birthplace of Bourbon Street, beignets, gumbo, and Mardi Gras revelry.',
                'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=600&q=80','🍜 Foodie',0,null],
            ['Hawaii - Maui','USA','america','beach','relaxed',3000,
                'Road to Hana, Haleakalā crater sunrise, whale watching, and perfect tropical beaches.',
                'https://images.unsplash.com/photo-1542258045550-2e818347c3d8?w=600&q=80',null,0,null],
            ['Banff','Canada','america','mountain','adventurous',2400,
                'Turquoise glacial lakes, Rocky Mountain peaks, and incredible wildlife in Alberta\'s crown jewel.',
                'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=600&q=80',null,0,null],
            ['Mexico City','Mexico','america','food_culture','cultural',1200,
                'Ancient Aztec capital reborn — Frida Kahlo museum, Zócalo, and greatest food scene in the Americas.',
                'https://images.unsplash.com/photo-1585464231875-d9ef1f5ad396?w=600&q=80','🍜 Foodie',0,null],
            ['Tulum','Mexico','america','beach','relaxed',1600,
                'Cliffside Mayan ruins above turquoise Caribbean, cenote swimming, and chic eco-resort scene.',
                'https://images.unsplash.com/photo-1601918774946-25832a4be0d6?w=600&q=80',null,0,null],
            // Hidden gems — Americas
            ['Iguazu Falls','Argentina','america','eco_tourism','adventurous',1800,
                'Wider than Niagara, taller than Victoria — 275 waterfalls thundering through subtropical jungle.',
                'https://images.unsplash.com/photo-1582610116397-edb72c1f6934?w=600&q=80','🌿 Eco',0,null],
            ['Patagonia','Argentina','america','eco_tourism','adventurous',2800,
                'End of the world — Fitz Roy mountain, Perito Moreno glacier, and condors overhead.',
                'https://images.unsplash.com/photo-1590420485460-4f7c26c73e57?w=600&q=80','🌿 Eco',1,95],
            ['Medellín','Colombia','america','trending','cultural',1100,
                'Colombia\'s most transformed city — cable cars, eternal spring climate, and flower festival.',
                'https://images.unsplash.com/photo-1596422846543-75c6fc197f11?w=600&q=80','🔥 Trending',1,88],
            ['Salar de Uyuni','Bolivia','america','eco_tourism','adventurous',1600,
                'World\'s largest salt flat — perfect mirror reflections in the wet season, alien landscapes all year.',
                'https://images.unsplash.com/photo-1560419015-7c427e8ae5ba?w=600&q=80','⭐ AI Pick',1,94],
            ['Atacama Desert','Chile','america','eco_tourism','adventurous',2200,
                'Driest non-polar desert — geyser fields, Moon Valley, flamingo lagoons, and unrivalled stargazing.',
                'https://images.unsplash.com/photo-1560419015-7c427e8ae5ba?w=600&q=80','🌿 Eco',0,null],
            ['Easter Island','Chile','america','historical','adventurous',3500,
                'Remote Pacific island of 900 mysterious moai statues built by the Rapa Nui civilisation.',
                'https://images.unsplash.com/photo-1554795397-6e0c2d70f06b?w=600&q=80','🏛️ Historic',1,97],
            ['Oaxaca','Mexico','america','food_culture','foodie',1100,
                'Indigenous capital of mole sauce, mezcal, Day of the Dead, and incredible artisan crafts.',
                'https://images.unsplash.com/photo-1518638150340-f706e86654de?w=600&q=80','🍜 Foodie',1,92],
            ['Costa Rica - Monteverde','Costa Rica','america','eco_tourism','eco',1700,
                'Cloud forest of hanging bridges, quetzal birds, zip-lining, and Costa Rica\'s green commitment.',
                'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&q=80','🌿 Eco',0,null],
            ['Valparaíso','Chile','america','trending','cultural',900,
                'Colourful hillside city — street art, funiculars, and bohemian soul.',
                'https://images.unsplash.com/photo-1560419015-7c427e8ae5ba?w=600&q=80','🎨 Street Art',1,94],
            ['Salento','Colombia','america','eco_tourism','adventurous',500,
                'Wax palm valley — Colombia\'s national tree, coffee fincas, and colourful architecture.',
                'https://images.unsplash.com/photo-1597976836977-6e1a0e6e6c87?w=600&q=80','🌴 Wax Palms',1,95],
            ['Tayrona','Colombia','america','beach','relaxed',700,
                'Jungle meets Caribbean — Sierra Nevada backdrop, hammocks, and indigenous heritage.',
                'https://images.unsplash.com/photo-1597976836977-6e1a0e6e6c87?w=600&q=80','🏝️ Jungle Beach',1,95],
            ['San Blas Islands','Panama','america','beach','relaxed',600,
                'Kuna Yala archipelago — autonomous indigenous region with 365 pristine islands.',
                'https://images.unsplash.com/photo-1589985270826-4b7bb135bc9d?w=600&q=80','🌴 Kuna Paradise',1,95],
            ['Cuenca','Ecuador','america','historical','cultural',600,
                'Ecuador\'s most beautiful city — domes, cobblestones, and Panama hats.',
                'https://images.unsplash.com/photo-1589985270826-4b7bb135bc9d?w=600&q=80','🎩 Hat City',1,92],
            ['Yellowstone','USA','america','eco_tourism','adventurous',2200,
                'World\'s first national park — Old Faithful geysers, hot springs, and bison on every road.',
                'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&q=80','🌿 Eco',0,null],
            // ── OCEANIA ─────────────────────────────────────────────────────
            ['Sydney','Australia','oceania','general','relaxed',2600,
                'Opera House, Harbour Bridge, Bondi Beach, and the world\'s most beautiful natural harbour.',
                'https://images.unsplash.com/photo-1524293581917-878a6d017c71?w=600&q=80',null,0,null],
            ['Melbourne','Australia','oceania','food_culture','cultural',2400,
                'Coffee capital and street-art city — laneways, Great Ocean Road, and incredible multiculturalism.',
                'https://images.unsplash.com/photo-1524293581917-878a6d017c71?w=600&q=80',null,0,null],
            ['Great Barrier Reef','Australia','oceania','eco_tourism','adventurous',2800,
                'World\'s largest coral ecosystem — 2,900 individual reefs and 900 islands off Queensland.',
                'https://images.unsplash.com/photo-1501426026826-31c667bdf23d?w=600&q=80','🌿 Eco',0,null],
            ['Uluru','Australia','oceania','historical','cultural',2400,
                'Sacred Anangu sandstone monolith glowing ochre at sunset — heart of the Red Centre.',
                'https://images.unsplash.com/photo-1529922236-4f2b4d2cc7ef?w=600&q=80','⭐ AI Pick',0,null],
            ['Queenstown','New Zealand','oceania','mountain','adventurous',2800,
                'Adrenaline capital of the world — bungee jumping, skiing, fjords, and Lord of the Rings scenery.',
                'https://images.unsplash.com/photo-1469521669194-babb45599def?w=600&q=80','🏔️ Adventure',0,null],
            ['Milford Sound','New Zealand','oceania','eco_tourism','adventurous',3000,
                'Fiordland\'s most dramatic fjord — sheer 1,200m cliffs, waterfalls, seals, and dolphins.',
                'https://images.unsplash.com/photo-1507699622108-4be3abd695ad?w=600&q=80','🌿 Eco',0,null],
            ['Bora Bora','French Polynesia','oceania','beach','romantic',4500,
                'Mount Otemanu rising above a perfect turquoise lagoon — the ultimate South Pacific fantasy.',
                'https://images.unsplash.com/photo-1589979481223-deb893043163?w=600&q=80','💝 Romantic',0,null],
            // Hidden gems — Oceania
            ['Fiji - Yasawa Islands','Fiji','oceania','beach','relaxed',2500,
                'Remote Melanesian island chain of extraordinary beaches, snorkelling, and traditional village life.',
                'https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=600&q=80','🌊 Beach',1,93],
            ['Tasmania','Australia','oceania','eco_tourism','adventurous',2200,
                'Island wilderness of Cradle Mountain, Bay of Fires, MONA museum, and pristine rainforest.',
                'https://images.unsplash.com/photo-1529922236-4f2b4d2cc7ef?w=600&q=80',null,1,91],
            ['Lord Howe Island','Australia','oceania','eco_tourism','relaxed',2800,
                'Limited to 400 visitors — endemic species, Ball\'s Pyramid, and a pristine lagoon.',
                'https://images.unsplash.com/photo-1524293581917-878a6d017c71?w=600&q=80','🏝️ 400 Only',1,97],
            ['Stewart Island','New Zealand','oceania','eco_tourism','adventurous',2200,
                'Kiwis in the wild — 85% national park, spectacular birdlife, and southern lights.',
                'https://images.unsplash.com/photo-1469521669194-babb45599def?w=600&q=80','🐦 Kiwi Island',1,95],
        ];
    }
}
