import laravel from 'laravel-vite-plugin';
import { defineConfig } from 'vite';

export default defineConfig({
    server: {
        port: 5173,
        strictPort: false,
    },
    plugins: [
        laravel({
            input: [
                'resources/css/app.css',
                'resources/css/blade/base.css',
                'resources/css/blade/layouts/app.css',
                'resources/css/blade/layouts/guest.css',
                'resources/css/blade/auth/confirm-password.css',
                'resources/css/blade/auth/forgot-password.css',
                'resources/css/blade/auth/login.css',
                'resources/css/blade/auth/register.css',
                'resources/css/blade/auth/reset-password.css',
                'resources/css/blade/auth/verify-email.css',
                'resources/css/blade/accommodations/index.css',
                'resources/css/blade/chat/index.css',
                'resources/css/blade/community/index.css',
                'resources/css/blade/dashboard/index.css',
                'resources/css/blade/destinations/index.css',
                'resources/css/blade/discover/index.css',
                'resources/css/blade/flights/index.css',
                'resources/css/blade/landing/index.css',
                'resources/css/blade/notifications/index.css',
                'resources/css/blade/pdf/itinerary.css',
                'resources/css/blade/plan-trip/index.css',
                'resources/css/blade/profile/edit.css',
                'resources/css/blade/wishlist/index.css',
                'resources/js/app.js',
                'resources/js/bootstrap.js',
                'resources/js/session-timeout.js',
                'resources/js/blade/base.js',
                'resources/js/blade/global.js',
                'resources/js/blade/login.js',
                'resources/js/blade/auth/register.js',
                'resources/js/blade/accommodations/index.js',
                'resources/js/blade/chat/index.js',
                'resources/js/blade/community/index.js',
                'resources/js/blade/dashboard/index.js',
                'resources/js/blade/destinations/index.js',
                'resources/js/blade/discover/index.js',
                'resources/js/blade/flights/index.js',
                'resources/js/blade/landing/index.js',
                'resources/js/blade/notifications/index.js',
                'resources/js/blade/pdf/itinerary.js',
                'resources/js/blade/plan-trip/index.js',
                'resources/js/blade/profile/edit.js',
                'resources/js/blade/wishlist/index.js',
            ],
            refresh: true,
        }),
    ],
});
